### ISSUE TITLE
Where does the software get its data from?

### ISSUE THREAD

**Issue by keilw** [soylent/device_map#1]
Hi,
I came across your Ruby port when looking for devicemap mirrors here on GitHub. Nice work. I can't tell from the CI server, if your code loads device-data from an acctual source (like the apache.org servers) or uses mocked test data instead?

Thanks,
Werner

**Comment by soylent** [comment]
Hi Werner

Thank you. This gem contains necessary Device Data files.
https://github.com/soylent/device_map/tree/master/lib/resources

When new version of Device Data is released, I simply update these resource files, run tests, and release a new gem version. There is no need to download Device Data files separately because I can just provide them together with the gem. And its size in this case is only 119 KB.

During gem installation I also parse and generate “optimized” device data files for later use. This improves performance significantly since we don’t need to parse the XML files every time during initialization.

**Comment by keilw** [comment]
Thanks, that sounds very interesting. Somewhere along the lines of what some committers to DeviceMap had in mind (with a NoSQL DB for the "optimized" data files to improve either size, performance or both) but so far it has not left concept phase, at least there's nothing I'm aware of either under apache.org or elsewhere. Out of curiosity, since the License is also Apache 2, would you consider to contribute some of this if the DeviceMap PMC was interested in such a contribution, too?

Some parts, mainly a JS library can be found on this mirror: https://github.com/apache/devicemap-browsermap 
That is among GitHub search results where I spotted yours, too.

Cheers,
Werner

**Comment by soylent** [comment]
Yes, absolutely.

**Comment by keilw** [comment]
Sounds great. Could you please send an email to Bertrand (he's also a Board member and helps the project as mentor primarily with process-related questions like this) See
http://devicemap.apache.org/team.html 
The (username) "at" apache.org

Either he can help you directly or point you to the right place. A general guideline about contributing to the Apache Foundation is here: https://community.apache.org/contributors/

Thanks,
Werner

**Comment by keilw** [comment]
I heard on the "dev" mailing list, you were already in touch with team members or your project seen. Are you subscribed to "devicemap-dev" ?

**Comment by soylent** [comment]
Yes, I am subscribed to the mailing list. I will get in touch with Bertrand.

**Comment by keilw** [comment]
Great, thanks. Sorry to quote your 2 followers there. IMHO with Travis CI and everything regardless of your number of followers, you show a far more professional attitute than @rezan and you certainly contributed so much more here, the GitHub stats are a wonderful way to see that;-)

**Comment by soylent** [comment]
Sorry, I had to delete your last message.

**Comment by keilw** [comment]
No worries, as long as you don't mind some messages on the dev-list (not usually my own) or feel scared. Bertrand will sure help you as we just help another committer to join.
